api_client:
  base_url: "https://api.exemple.com"
  version: "v1"
  timeout: 30
  retries: 3
  authentication:
    type: "Bearer"
    api_key: "votre_cle_api_ici"
  headers:
    Content-Type: "application/json"
    Accept: "application/json"
